# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V_Yta3mbdD_LsJ3lay5jTJlOJcDkIG7T
"""

print("Hello World")